[aws]
symbol = "  "
format = " [aws](italic) [$symbol $profile $region]($style)"
style = "bold blue"

[buf]
symbol = " "
format = " [buf](italic) [$symbol $version $buf_version]($style)"

[c]
symbol = " "
format = " [$symbol($version(-$name))]($style)"

[cmake]
symbol = " "

[conda]
symbol = " "
format = " conda [$symbol$environment]($style)"

[crystal]
symbol = " "

[dart]
symbol = " "
format = " dart [$symbol($version )]($style)"

[docker_context]
symbol = " "
format = " docker [$symbol$context]($style)"

[elixir]
symbol = " "
format = " exs [$symbol $version OTP $otp_version ]($style)"

[elm]
symbol = " "
format = " elm [$symbol($version )]($style)"

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "
style = "italic bright-blue"

[git_status]
style = "bold italic bright-blue"

[git_commit]
tag_symbol = '  '

[golang]
symbol = " "
format = " go [$symbol($version )]($style)"

[guix_shell]
symbol = " "

[haskell]
symbol = " "
format = " hs [$symbol($version )]($style)"

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[java]
symbol = " "
format = " java [${symbol}(${version} )]($style)"

[julia]
symbol = " "
format = " jl [$symbol($version )]($style)"

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "
format = " [py](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
style = "italic bright-yellow"

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[directory]
read_only = " 󰌾"
truncation_length = 2
truncation_symbol = "…/"
use_os_path_sep = true
style = "italic blue"
repo_root_style = 'bold blue'

[cmd_duration]
format = "[$duration](italic white)"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"
